# Project information
site_name: "Overfitting: From Algorithms to Silicon"
site_url: https://reiase.github.io
site_author: "reiase <reiase@gmail.com>"

site_description: >-
  Overfitting: Where we deliberately dive too deep into ML algorithms, 
  mathematical principles and hardware implementations.

exclude_docs: |
  Excalidraw/
  posts/imgs/*.md

# Copyright
copyright: Copyright &copy; 2023 - 2025 Reiase

# Configuration
theme:
  name: material
  language: zh
  custom_dir: overrides
  font:
      text: Source Han Sans SC
      code: Roboto Mono
  palette:
  # Light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    # accent: light blue
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  # Dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    # accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - awesome-pages
  - blog:
      blog_dir: .
      blog_toc: true
  - ezlinks:
        wikilinks: true
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      locale: zh
      custom_format: "%A %d %B %Y"
      enable_creation_date: true
  - minify:
      minify_html: true
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags:
      tags_file: tags.md

  - callouts
  - glightbox
  - markdown-exec

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: G-LMDTYMWWTF
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/reiase
extra_javascript:
  - javascripts/mathjax.js
  - https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/mathjax/3.2.0/es5/tex-mml-chtml.js
# Extensions
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - mdx_breakless_lists
  - meta
  - nl2br
  - sane_lists
  - smarty
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - 博客:
    - index.md
  - 标签: tags.md
  - ...